const Emojis = require(`../config/emojis.config`);

const eatsPep = `\\*eats pep\\*`;
const snapIn = `\\*pops into existence\\*`;
const snapOut = `\\*pops out of existence\\*`;
const notHere = `Frumpkin isn't around`;

const frumpkinPhrases = [
  `\\*blinks\\*`,
  `\\*chases tail\\*`,
  `${Emojis.pepeeyes}`,
  `mew`,
  `meeeeeeeeew!!!`,
  `owo`,
  `${Emojis.blobcatknife}`,
  `${Emojis.catknife}`,
  `${Emojis.bananacat}`,
  `${Emojis.googlecat} mew `,
  `\\*purrs\\*`,
  `${Emojis.googlecatheart}`,
  `\\*wiggles, ready to pounce\\*`,
  `\\*pounces\\*`,
  `\\*licks ur face\\*`,
  `\\*licks paw\\*`,
  `\\*sticks leggy up in the air\\*`,
  `\\*RUNS AROUND\\*`,
  `\\*bites ur arm lovingly\\*`,
  `${Emojis.headpat}`,
  `\\*trots over to bed\\*`,
  `\\*curls up to sleep\\*`,
  `\\*ATTACKS U\\*`,
  `\\*attacks paper\\*`,
  `\\*murders mousey\\*`,
  `\\*sits at the door waiting to be let out\\*`,
  `\\*sniffs empty food bowl\\*`,
  `\\*claws ur leg while climbing onto you\\*`,
  `\\*farts\\*`,
  `\\*jingle jingle\\*`,
  `\\*licks self\\*`,
  `\\*tries to eat ur food\\* `,
  `\\*laps up water\\*`,
  `\\*stares\\*`,
  `\\*blinks\\*`,
  `\\*BIG MOON EYES\\*`,
  `\\*ignores full food bowl\\*`,
  `\\*kneads blankie\\*`,
  `\\*chews cables\\*`,
  `\\*licks teacup\\*`,
  `\\*steals a post-it\\*`,
  `\\*yawns\\*`,
  `\\*arches back and stretches\\*`,
  `\\*jumps off table\\*`,
  `\\*attacks blanket\\*`,
  `\\*spills water bowl while ur back is turned\\*`,
  `\\*meows so everyone knows hes going to the bathroom\\*`,
  `miiiiw!!!`,
  `\\*hides under dresser\\*`,
  `\\*sits on ur lap\\*`,
  `${Emojis.kittyplay}`,
  `${Emojis.bongocat}`,
  `${Emojis.grabhandL} \\*swipes\\*`,
  `\\*is stinky\\*`,
  `\\*trots with his tail up in the air like a happy little boi\\*`,
  `\\*zooms through shark tunnel\\*`,
  `\\*jumps on shark tunnel\\*`,
  `\\*rummages through toybox\\*`,
  `\\*meows for attention and then runs away\,*`,
  `\\*hides\\*`,
  `\\*murders rattle bird\\*`,
  `\\*carries toy around\\*`,
  `\\*appears with bath plug\\*`,
  `\\*tears feather duster to sheads\\*`,
  `\\*uses ur shoulders as a launch pad\\*`
];

module.exports = {
  eatsPep,
  snapIn,
  snapOut,
  notHere,
  frumpkinPhrases
};